include:
  - Misc:
    - Contest:
      - Makefile:
        - misc/Makefile
    - 'How Did We Get Here?':
      - Macros:
        - misc/speed/macros.tex
        - misc/speed/macros.hpp
      - constexpr:
        - misc/speed/constexpr.tex
      - Bump Allocator:
        - misc/speed/bump-allocator.hpp
    - Tools:
      - SplitMix64:
        - misc/splitmix64.hpp
      - x86 Stack Hack:
        - misc/stack-size.hpp
    - Algorithms:
      - Bit Hacks:
        - misc/bit-hacks.hpp
      - DP opt:
        - Aliens:
          - misc/aliens.hpp
        - DnC DP:
          - misc/dnc-dp.tex
          - misc/dnc-dp.hpp
        - Knuth's Opt:
          - misc/knuth-dp.tex
      - Mo's Algorithm on Tree:
        - misc/mo-tree.hpp
  - Data Structures:
    - GNU PBDS:
      - ds/pbds.hpp
      - ds/order-stats.hpp
    - Persistent seg tree:
      - ds/persist.hpp
    - Line Container:
      - ds/line-container.hpp
    - Li-Chao Tree:
      - ds/li-chao.hpp
    - Wavelet Matrix:
      - ds/wavelet-matrix.hpp
    - Link-Cut Tree:
      - ds/lct.hpp
    - Dynamic MST:
      - ds/dyn-mst.hpp
  - Graph:
    - Modeling:
      - graph/model.tex
    - Low link:
      - graph/lowlink.hpp
    - Shortest paths:
      - Dial's algorithm:
        - graph/dial.hpp
    - Matching/Flows:
      - Dinic's Algorithm:
        - graph/flows/dinic.hpp
      - Minimum Cost Flow:
        - graph/flows/min-cost-flow.hpp
      - Gomory-Hu Tree:
        - graph/flows/gomory-hu.hpp
      - Global Minimum Cut:
        - graph/flows/global-min-cut.hpp
      - Bipartite Minimum Cover:
        - graph/flows/min-bi-cover.hpp
    - Strongly Connected Components:
      - graph/scc.hpp
      - 2-Satisfiability:
        - graph/2sat.hpp
    - Manhattan Distance MST:
      - graph/manhattan-mst.hpp
    - Functional graph:
      - Loops:
        - graph/func.hpp
  - Math:
    - Number Theory:
      - Theorems:
        - math/number-theory/theorems.tex
      - Euler's Totient Function:
        - math/number-theory/totient.hpp
      - Möbius Function:
        - math/number-theory/mobius.hpp
      - Mod Struct:
        - math/number-theory/modular.tex
        - math/number-theory/modular.hpp
      - Miller-Rabin:
        - math/number-theory/miller-rabin.hpp
      - Pollard's Rho:
        - math/number-theory/pollard-rho.hpp
    - Combinatorics:
      - Formulas:
        - math/combinatorics/formulas.tex
      - Stirling:
        - math/combinatorics/stirling.hpp
      - Extended Lucas:
        - math/combinatorics/lucas.hpp
    - Theorems:
      - math/theorems.tex
  - Numeric:
    - Fast Fourier Transform:
      - numeric/fft.hpp
      - numeric/fft-usage.hpp
    - Fast Walsh-Hadamard Transform:
      - numeric/fwht.hpp
    - Subset Convolution:
      - numeric/subset-convolution.hpp
    - Linear Recurrences:
      - Berlekamp-Massey Algorithm:
        - numeric/berlekamp-massey.hpp
      - Linear Recurrence Calculation:
        - numeric/linear-recurrence.hpp
    - Matrices:
      - Determinant:
        - numeric/det-mod.hpp
        - numeric/det-double.hpp
      - Solve Linear Equation:
        - numeric/linear-eq.hpp
      - Freivalds' algo:
        - numeric/freivalds.tex
    - Polynomial Interpolation:
      - numeric/interpolation.hpp
  - Geometry:
    - Point:
      - geometry/point.hpp
      - Spherical Coordinates:
        - geometry/spherical.hpp
    - Segments:
      - geometry/segments.hpp
    - Pick's theorem:
      - geometry/pick.tex
    - Convex Hull:
      - geometry/convex-hull.hpp
    - Angular Sort:
      - geometry/angular-sort.hpp
    - Convex Polygon Minkowski Sum:
      - geometry/minkowski-sum.hpp
    - Point In Polygon:
      - geometry/point-inclusion.hpp
      - Convex Version:
        - geometry/convex-inclusion.hpp
      - Offline Multiple Points Version:
        - geometry/multi-inclusion.hpp
    - Closest Pair:
      - geometry/closest-pair.hpp
  - Strings:
    - Knuth-Morris-Pratt Algorithm:
      - strings/kmp.hpp
    - Suffix Array:
      - strings/suffix-array.hpp
    - Z Value:
      - strings/z-value.hpp
    - Manacher's Algorithm:
      - strings/manacher.hpp
    - Minimum Rotation:
      - strings/min-rotation.hpp
    - Palindromic Tree:
      - strings/palindromic-tree.hpp
  - Debug List:
    - misc/debug-list.md
  - Tech:
    - misc/techniques.md

dependencies:
  show: true
  ignore_cycles: false
