include:
  - Misc:
    - Debug List:
      - misc/debug-list.md
    - Algorithms:
      - DP opt:
        - Aliens:
          - misc/ALIENS.hpp
        - DnC DP:
          - misc/DPDNC.hpp
        - Knuth's Opt:
          - misc/KNUTH.hpp
        - DP SOS:
          - misc/DPSOS.hpp
        - DP Open and Close:
          - misc/OPENCLOSE.hpp
      - Mo's Algorithm:
        - misc/MO.hpp
      - Mo's Algorithm on Tree:
        - misc/MOTREE.hpp
      - Ternary search:
        - misc/TERSEARCH.hpp
  - Data Structures:
    - Implicit Segment Tree:
      - ds/IMPSEG.hpp
    - Persistent Segment Tree:
      - ds/PERSEG.hpp
    - Persistent Trie:
      - ds/PERTRIE.hpp
    - 2D Fenwick Tree:
      - ds/BIT2D.hpp
    - Line Container:
      - ds/LINECON.hpp
    - Wavelet Tree:
      - ds/WAVELET.hpp
    - Segtree Beats:
      - ds/SEGBEATS.hpp
    - Dynamic Connectivity:
      - ds/DYNCON.hpp
  - Graph:
    - SCC:
      - Kosaraju:
        - graph/SCC.hpp
      - 2SAT:
        - graph/2SAT.hpp
    - Matching/Flows:
      - Edmonds-Karp:
        - graph/EDMOND.hpp
      - Dinic:
        - graph/DINIC.hpp
      - Min-cost Flow:
        - graph/MCF.hpp
      - Kuhn:
        - graph/KUHN.hpp
    - Eulerian cycle:
      - graph/EULERCYCLE.hpp
    - Bridge Tree:
      - graph/BRIDGE.hpp
    - Block cut Tree:
      - graph/BLOCKCUT.hpp
    - Bellman-Ford:
      - graph/BELLMAN.hpp
    - HLD:
      - graph/HLD.hpp
  - Math:
    - Chinese Remainder Theorem:
      - math/CRT.hpp
    - Diophantine Equation:
      - math/DIOPHAN.hpp
    - Miller-Rabin:
      - math/MILRAB.hpp
    - Pollard's Rho:
      - math/POLRHO.hpp
    - Gaussian Elimination:
      - math/GAUSS.hpp
    - FFT:
      - math/FFT.hpp
    - General Lucas' Theorem:
      - math/LUCAS.hpp
  - Geometry:
    - Pick's theorem:
      - geometry/pick.tex
    - Chebyshev Distance:
      - geometry/CHEBYSHEV.hpp
    - Convex Hull:
      - geometry/CONHUL.hpp
    - Polygon Area:
      - geometry/AREAPOL.hpp
    - Minkowski Sum:
      - geometry/MOOSUM.hpp
    - Point In Polygon:
      - geometry/CHECKPTIN.hpp
    - Closest Pair:
      - geometry/CLOSESTPAIR.hpp
  - Strings:
    - Aho-Corasick Automaton:
      - strings/AHO.hpp
    - Knuth-Morris-Pratt Algorithm:
      - strings/KMP.hpp
    - Suffix Array:
      - strings/SUFARR.hpp
    - Z Algorithm:
      - strings/ZFUNC.hpp
    - Manacher's Algorithm:
      - strings/MANA.hpp

dependencies:
  show: true
  ignore_cycles: false
